tasks:
  - before: |
      pip install pre-commit
      pre-commit install --install-hooks
      pip install -e .
      # `duckling` compatbility issue.
      pip install --force-reinstall JPype1==0.6.3
      yarn install --cwd=config_to_bot/debugger/
image:
  file: .gitpod.Dockerfile
